name: CI

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.12.0
            otp: 24.0
            check_formatted: true
            warnings_as_errors: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-elixir@v1.5.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          experimental-otp: true
      - name: Install packages
        run: |
          sudo apt-get install -y -qq inotify-tools
      - run: mix format --check-formatted
        if: matrix.check_formatted
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - run: mix compile --warnings-as-errors
        if: matrix.warnings_as_errors
      - run: mix test
